### ISSUE TITLE
__toString()

### ISSUE THREAD

**Issue by OskarStark** [Roave/Dont#18]
What about don’t __toString() as you cannot throw exceptions?

**Comment by asgrim** [comment]
Since PHP 7.4+ allows exceptions to be thrown in `__toString()` the benefit for that specific reason is limited.

That said, there is still good reasoning to ban `__toString()` - see here: https://github.com/ShittySoft/symfony-live-berlin-2018-doctrine-tutorial/pull/3#issuecomment-460441229

**Comment by Ocramius** [comment]
Please do send a patch: good addition :+1: 

Also, not a problem (IMO) to bump to 7.4 either: past releases still valid anyway
