### ISSUE TITLE
[ RFC ] Would it be appreciated if I add the new magic methods to Dont(De)serialize?

### ISSUE THREAD

**Issue by lexidor** [Roave/Dont#21]
### [Update notes](https://www.php.net/manual/en/migration74.new-features.php#migration74.new-features.standard.magic-serialize)

PHP7.4 added `__unserialize()` and `__serialize()`, which take precedence over `__sleep()` and `__wakeup()` if they are present. By default using `DontSerialize` will do the trick, but someone extending your class might not see you `use` statement and implement `__serialize()` /accidentally/.

This would be a backwards incompatible change, but I think this is more in line with the programmers intent.

Please use @lexidor in your response to make sure I don't forget.

**Comment by Ocramius** [comment]
I don't think this would be a BC break, since implementing `DontSerialize` and `__serialize()` is very much a SNAFU.

Can the methods be *added*, or do they need replacing?

**Comment by lexidor** [comment]
If this library can be used on PHP 7.3 and 7.4 the trait needs both `__sleep()` + `__wakeup()` and `__serialize()` + `__unserialize()`. PHP 7.3 won't understand `__serialize()` and will call `__sleep()` and PHP 7.4 will understand `__serialize()` and call that one if it is present.

The implementation of both methods can be the same or `__serialize()` can manually call `__sleep()` to have the same effect.

English is not my first language and _SNAFU_ (Status Nominal: All Fucked Up) is a bit unclear to me. Could you tell me what you meant?

**Comment by lexidor** [comment]
### [Serializable](https://www.php.net/manual/en/class.serializable.php)

This trait was already bypassable by implementing `Serializable` and providing the methods `serialize()` and `unserialize()`. These method do not have underscores in them and should not be confused with the ones that do.

This is not a PHP 7.4 feature, but a PHP 5.1 one.

The complete implementation of `DontSerialize` needs `__sleep()`, `serialize()`, and `__serialize()`.

**Comment by Ocramius** [comment]
Careful: Serializable is a declaration of serializability! If you implement
Serializable and make your things `throw` all the time, you are lying to
your consumers.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by lexidor** [comment]
I understand, I won't implement the interface. I'll just implement the methods. This means that a child class implementer will get a fatal error when they try to redeclare a final method. `$x instanceof Serializable` will still be false. This should behave exactly the same as your final public `__sleep()`.

I have understood the concerns and will make the PR shortly.

**Comment by lexidor** [comment]
Sorry, English is not my first language.
I don't quite understand what this means.
![image](https://user-images.githubusercontent.com/31805625/71782841-f487b100-2fde-11ea-8c43-7461b5379b40.png)
What can I do to make the test pass with a green checkmark?

**Comment by Ocramius** [comment]
I think that's because coverage decreased

**Comment by lexidor** [comment]
I can't make it hit 100%, because PHP 7.3 will never call `__unserialize()` and PHP 7.3 will never call `__wakeup()`.

**Comment by Ocramius** [comment]
I think the only way to cover this directly is to call these methods explicitly inside a test case

**Comment by lexidor** [comment]
Will do
