### ISSUE TITLE
Would PHP 8.1 RC6 be stable enough to test compatibility

### ISSUE THREAD

**Issue by rvanlaak** [Roave/Dont#36]
Commit 9562e923e14e5d2c1b58bc006f24423b102e932c pinned the library to `8.0.*`. 

Given PHP 8.1 released the RC phaze and is released soon, will this be the right time to check whether `roave/dont` is compatible?

If so, I'm happy to verify and test, and file a PR thereafter.

**Comment by Ocramius** [comment]
Yes please: enabling CI for `8.1.0`, and verifying that everything works as expected, would allow defining `"php": "~8.0.0 || ~8.1.0"` in the requirements.

Please do send a patch :)

**Comment by azjezz** [comment]
Huh, just saw this issue after i sent #37 😄

**Comment by Ocramius** [comment]
Handled in #37 - releasing now :)
